-- EventFlow Database Setup Script
-- Run this in MySQL Workbench or MySQL Command Line

-- Create Database
CREATE DATABASE IF NOT EXISTS eventflow;
USE eventflow;

-- Users Table
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_role (role)
);

-- Admins Table
CREATE TABLE IF NOT EXISTS admins (
  id INT PRIMARY KEY AUTO_INCREMENT,
  admin_id VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_admin_id (admin_id)
);

-- Events Table
CREATE TABLE IF NOT EXISTS events (
  id INT PRIMARY KEY AUTO_INCREMENT,
  event_name VARCHAR(200) NOT NULL,
  club_name VARCHAR(100) NOT NULL,
  event_date DATE NOT NULL,
  event_time TIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT,
  capacity INT DEFAULT 100,
  admin_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
  INDEX idx_event_date (event_date),
  INDEX idx_admin_id (admin_id)
);

-- Registrations Table
CREATE TABLE IF NOT EXISTS registrations (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  event_id INT NOT NULL,
  registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_registration (user_id, event_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  INDEX idx_user_id (user_id),
  INDEX idx_event_id (event_id)
);

-- Optional: Create Demo Admin Account
-- Password for both: password123 (hashed version will be generated by backend)
INSERT INTO admins (admin_id, name, password) VALUES 
('ADMIN001', 'Demo Administrator', '$2a$10$dXJ3SW6G7P50eS3xLHGJr.NrKVLJiznN9SzC9dJYhVHwqJqH8nN0K') 
ON DUPLICATE KEY UPDATE id=id;

-- Optional: Create Demo User Account
INSERT INTO users (name, email, password, phone, role) VALUES 
('Demo User', 'demo@example.com', '$2a$10$dXJ3SW6G7P50eS3xLHGJr.NrKVLJiznN9SzC9dJYhVHwqJqH8nN0K', '+1234567890', 'user') 
ON DUPLICATE KEY UPDATE id=id;

-- Display confirmation
SELECT 'Database setup completed successfully!' AS Status;
SELECT 'Users table' AS Table_Name, COUNT(*) AS Record_Count FROM users
UNION ALL
SELECT 'Admins table', COUNT(*) FROM admins
UNION ALL
SELECT 'Events table', COUNT(*) FROM events
UNION ALL
SELECT 'Registrations table', COUNT(*) FROM registrations;
